import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

const useIterator =  (url: string) => {

  const [users, setUsers]       = useState([]);
  const [userList, setUserList] = useState([]);
  const [current, setCurrent]   = useState(0);

  let loading = false;

  const previous = async () => {

    if(current <= 1) return;

    setUserList(users[current - 2]);

    setCurrent((prevState) => 
      prevState - 1
    );

  }

  const next = async () => {

    if(current != 0 && current < users?.length){

      setUserList(users[current]);

      setCurrent((prevState) => 
        prevState + 1
      );

      return ;
    }

    const response = await axios.get(`${url}`);

    setUsers([...users, response?.data?.results]);

    setUserList(response?.data.results)

    setCurrent((prevState) => 
      prevState + 1
    );

  }


  return [
      users,
      userList,
      current,
      loading,
      previous, 
      next
  ]
}

export default function Home() {

  const [users, userList, current, loading, previous, next] = useIterator("https://randomuser.me/api");
  
  return (
    <>
      <Head>
        <title>Random User with prev, current & next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.all}>
          {Array.isArray(users) && users?.map((user: object, key: number) => (
            <div key={key}>
              <img src={`${user[0]?.picture?.thumbnail}`} />
              <h1>{user[0]?.name?.title} {user[0]?.name?.first} {user[0]?.name?.last}</h1>
            </div>
          ))}
        </div>

        <h1>Current User</h1>
        {Array.isArray(userList) && userList?.map((user: object, key: number) => (
          <div key={key}>
            <img src={`${user?.picture?.thumbnail}`} />
            <h1>{user?.name?.title} {user?.name?.first} {user?.name?.last}</h1>
          </div>
        ))}
        <button onClick={previous}>Prev</button>
        <button onClick={next}>Next</button>
      </main>
    </>
  )
}
